// <auto-generated />
using FleetManager.Infrastructure.EntityFramework.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FleetManager.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250617132853_AddedDiagnosticsAndSeeds")]
    partial class AddedDiagnosticsAndSeeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("FleetManager.Domain.Entities.Diagnostics.DiagnosticProtocol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("VehicleType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DiagnosticProtocols");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Truck Diagnostic Protocol",
                            VehicleType = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bus Diagnostic Protocol",
                            VehicleType = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Car Diagnostic Protocol",
                            VehicleType = 0
                        });
                });

            modelBuilder.Entity("FleetManager.Domain.Entities.Diagnostics.ErrorCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProtocolId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProtocolId");

                    b.ToTable("ErrorCodes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "T001",
                            Description = "Engine Overheating",
                            ProtocolId = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "T002",
                            Description = "Low Oil Pressure",
                            ProtocolId = 1
                        },
                        new
                        {
                            Id = 3,
                            Code = "T003",
                            Description = "Fuel System Leak",
                            ProtocolId = 1
                        },
                        new
                        {
                            Id = 4,
                            Code = "T004",
                            Description = "Brake Air Pressure Low",
                            ProtocolId = 1
                        },
                        new
                        {
                            Id = 5,
                            Code = "T005",
                            Description = "Battery Voltage Low",
                            ProtocolId = 1
                        },
                        new
                        {
                            Id = 6,
                            Code = "T006",
                            Description = "Transmission Oil Overheating",
                            ProtocolId = 1
                        },
                        new
                        {
                            Id = 7,
                            Code = "B001",
                            Description = "Passenger Door Sensor Fault",
                            ProtocolId = 2
                        },
                        new
                        {
                            Id = 8,
                            Code = "B002",
                            Description = "AC Compressor Failure",
                            ProtocolId = 2
                        },
                        new
                        {
                            Id = 9,
                            Code = "B003",
                            Description = "Brake Air Pressure Low",
                            ProtocolId = 2
                        },
                        new
                        {
                            Id = 10,
                            Code = "B004",
                            Description = "Wheel Speed Sensor Failure",
                            ProtocolId = 2
                        },
                        new
                        {
                            Id = 11,
                            Code = "B005",
                            Description = "Communication Bus Error",
                            ProtocolId = 2
                        },
                        new
                        {
                            Id = 12,
                            Code = "C001",
                            Description = "Engine Overheating",
                            ProtocolId = 3
                        },
                        new
                        {
                            Id = 13,
                            Code = "C002",
                            Description = "Low Brake Fluid",
                            ProtocolId = 3
                        },
                        new
                        {
                            Id = 14,
                            Code = "C003",
                            Description = "Low Tire Pressure",
                            ProtocolId = 3
                        },
                        new
                        {
                            Id = 15,
                            Code = "C004",
                            Description = "Battery Voltage Low",
                            ProtocolId = 3
                        },
                        new
                        {
                            Id = 16,
                            Code = "C005",
                            Description = "Fuel System Leak",
                            ProtocolId = 3
                        });
                });

            modelBuilder.Entity("FleetManager.Domain.Entities.Diagnostics.Sensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProtocolId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProtocolId");

                    b.ToTable("Sensors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Engine Coolant Temperature",
                            ProtocolId = 1,
                            Unit = "°C"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Engine Speed (RPM)",
                            ProtocolId = 1,
                            Unit = "RPM"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Oil Pressure",
                            ProtocolId = 1,
                            Unit = "Bar"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Fuel Level",
                            ProtocolId = 1,
                            Unit = "%"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Battery Voltage",
                            ProtocolId = 1,
                            Unit = "V"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Brake Air Pressure",
                            ProtocolId = 1,
                            Unit = "Bar"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Transmission Oil Temperature",
                            ProtocolId = 1,
                            Unit = "°C"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Engine Coolant Temperature",
                            ProtocolId = 2,
                            Unit = "°C"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Engine Speed (RPM)",
                            ProtocolId = 2,
                            Unit = "RPM"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Fuel Level",
                            ProtocolId = 2,
                            Unit = "%"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Passenger Door Status",
                            ProtocolId = 2,
                            Unit = ""
                        },
                        new
                        {
                            Id = 12,
                            Name = "AC Compressor Status",
                            ProtocolId = 2,
                            Unit = ""
                        },
                        new
                        {
                            Id = 13,
                            Name = "Brake Air Pressure",
                            ProtocolId = 2,
                            Unit = "Bar"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Wheel Speed Front Axle",
                            ProtocolId = 2,
                            Unit = "km/h"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Engine Coolant Temperature",
                            ProtocolId = 3,
                            Unit = "°C"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Engine Speed (RPM)",
                            ProtocolId = 3,
                            Unit = "RPM"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Oil Pressure",
                            ProtocolId = 3,
                            Unit = "Bar"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Fuel Level",
                            ProtocolId = 3,
                            Unit = "%"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Battery Voltage",
                            ProtocolId = 3,
                            Unit = "V"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Brake Fluid Level",
                            ProtocolId = 3,
                            Unit = "%"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Tire Pressure",
                            ProtocolId = 3,
                            Unit = "PSI"
                        });
                });

            modelBuilder.Entity("FleetManager.Domain.Entities.Vehicle", b =>
                {
                    b.Property<string>("ChassisSeries")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<uint>("ChassisNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DiagnosticProtocolId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.HasKey("ChassisSeries", "ChassisNumber");

                    b.HasIndex("DiagnosticProtocolId");

                    b.ToTable("Vehicles");

                    b.HasDiscriminator<string>("VehicleType").HasValue("Vehicle");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FleetManager.Domain.Entities.Bus", b =>
                {
                    b.HasBaseType("FleetManager.Domain.Entities.Vehicle");

                    b.HasDiscriminator().HasValue("Bus");
                });

            modelBuilder.Entity("FleetManager.Domain.Entities.Car", b =>
                {
                    b.HasBaseType("FleetManager.Domain.Entities.Vehicle");

                    b.HasDiscriminator().HasValue("Car");
                });

            modelBuilder.Entity("FleetManager.Domain.Entities.Truck", b =>
                {
                    b.HasBaseType("FleetManager.Domain.Entities.Vehicle");

                    b.HasDiscriminator().HasValue("Truck");
                });

            modelBuilder.Entity("FleetManager.Domain.Entities.Diagnostics.ErrorCode", b =>
                {
                    b.HasOne("FleetManager.Domain.Entities.Diagnostics.DiagnosticProtocol", "Protocol")
                        .WithMany("ErrorCodes")
                        .HasForeignKey("ProtocolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Protocol");
                });

            modelBuilder.Entity("FleetManager.Domain.Entities.Diagnostics.Sensor", b =>
                {
                    b.HasOne("FleetManager.Domain.Entities.Diagnostics.DiagnosticProtocol", "Protocol")
                        .WithMany("Sensors")
                        .HasForeignKey("ProtocolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Protocol");
                });

            modelBuilder.Entity("FleetManager.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("FleetManager.Domain.Entities.Diagnostics.DiagnosticProtocol", "DiagnosticProtocol")
                        .WithMany()
                        .HasForeignKey("DiagnosticProtocolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiagnosticProtocol");
                });

            modelBuilder.Entity("FleetManager.Domain.Entities.Diagnostics.DiagnosticProtocol", b =>
                {
                    b.Navigation("ErrorCodes");

                    b.Navigation("Sensors");
                });
#pragma warning restore 612, 618
        }
    }
}
