// <auto-generated />
using FleetManager.Infrastructure.EntityFramework.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FleetManager.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("FleetManager.Domain.Entities.Vehicle", b =>
                {
                    b.Property<string>("ChassisSeries")
                        .HasColumnType("TEXT");

                    b.Property<uint>("ChassisNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.HasKey("ChassisSeries", "ChassisNumber");

                    b.ToTable("Vehicles", t =>
                        {
                            t.Property("ChassisSeries")
                                .HasColumnName("Vehicle_ChassisSeries");

                            t.Property("ChassisNumber")
                                .HasColumnName("Vehicle_ChassisNumber");
                        });

                    b.HasDiscriminator<string>("VehicleType").HasValue("Vehicle");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FleetManager.Domain.Entities.Bus", b =>
                {
                    b.HasBaseType("FleetManager.Domain.Entities.Vehicle");

                    b.ToTable("Vehicles", t =>
                        {
                            t.Property("ChassisSeries")
                                .HasColumnName("Vehicle_ChassisSeries");

                            t.Property("ChassisNumber")
                                .HasColumnName("Vehicle_ChassisNumber");
                        });

                    b.HasDiscriminator().HasValue("Bus");
                });

            modelBuilder.Entity("FleetManager.Domain.Entities.Car", b =>
                {
                    b.HasBaseType("FleetManager.Domain.Entities.Vehicle");

                    b.ToTable("Vehicles", t =>
                        {
                            t.Property("ChassisSeries")
                                .HasColumnName("Vehicle_ChassisSeries");

                            t.Property("ChassisNumber")
                                .HasColumnName("Vehicle_ChassisNumber");
                        });

                    b.HasDiscriminator().HasValue("Car");
                });

            modelBuilder.Entity("FleetManager.Domain.Entities.Truck", b =>
                {
                    b.HasBaseType("FleetManager.Domain.Entities.Vehicle");

                    b.ToTable("Vehicles", t =>
                        {
                            t.Property("ChassisSeries")
                                .HasColumnName("Vehicle_ChassisSeries");

                            t.Property("ChassisNumber")
                                .HasColumnName("Vehicle_ChassisNumber");
                        });

                    b.HasDiscriminator().HasValue("Truck");
                });

            modelBuilder.Entity("FleetManager.Domain.Entities.Vehicle", b =>
                {
                    b.OwnsOne("FleetManager.Domain.ValueObjects.ChassisId", "ChassisId", b1 =>
                        {
                            b1.Property<string>("VehicleChassisSeries")
                                .HasColumnType("TEXT");

                            b1.Property<uint>("VehicleChassisNumber")
                                .HasColumnType("INTEGER");

                            b1.Property<uint>("Number")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ChassisNumber");

                            b1.Property<string>("Series")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("ChassisSeries");

                            b1.HasKey("VehicleChassisSeries", "VehicleChassisNumber");

                            b1.ToTable("Vehicles");

                            b1.WithOwner()
                                .HasForeignKey("VehicleChassisSeries", "VehicleChassisNumber");
                        });

                    b.Navigation("ChassisId")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
